import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'

import { useRouter } from 'next/router';

import Layout from '../components/layout';
import Hero from '../components/hero';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter(); 


  const TEXT_OLD_VERSION = "--> GO TO OLD VERSION";

  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    </Layout>
  )
}
